// ─── Stock Out — mock data ─────────────────────────────────────────────────────
//
// The invoice number is the unique identifier for each transaction.
// No system-generated transaction ID is used.
//
// listNumber/batchId groupings below are deliberately chosen to exercise
// every bulk-add code path on ScanItemsPage:
//   LIST-A     — CNT1 only (3 items, includes 1 Faulty) — single-shipment add
//                with the faulty warning modal.
//   LIST-B     — spans CNT1 (2 items) AND CNT2 (2 items, 1 Faulty) — triggers
//                the multi-shipment disambiguation modal; the CNT2 branch
//                also triggers the faulty warning after selection.
//   BATCH-001  — ASH1 only (2 items, both Ok) — single-shipment add with no
//                faulty warning.
//   CNT1-TTL-26-0001/0002/0003, CNT2-TTL-26-0001, ASH1-MWS-26-0001 — distinct
//                Batch IDs for exercising Method 3 (bulk by Batch ID).
//
// BACKEND INTEGRATION SEAM:
//   Replace with GET /stock-out — list of all completed transactions.
//   The inventory lookup (asset scan validation) will come from
//   GET /inventory/:assetId — not hardcoded here.

import type { StockOutTransaction, ScannedItem } from "./stockOutTypes";

// Mock inventory pool — represents items available for scanning during Stock Out.
// BACKEND INTEGRATION SEAM: GET /inventory?status=Ok,Faulty
export const mockInventoryPool: ScannedItem[] = [
  {
    assetId: "CNT1-TTL-26-0001",
    category: "Laptop",
    brand: "HP",
    model: "EliteBook 840 G8",
    processor: "Intel Core i5",
    generation: "11th Gen",
    ram: "8GB",
    storage: "256GB SSD",
    speed: "2.4GHz",
    screenType: "Non-Touch",
    status: "Ok",
    batchId: "CNT1-TTL-26-0001",
    shipmentId: "CNT1",
    listNumber: "LIST-A",
    source: "scan",
  },
  {
    assetId: "CNT1-TTL-26-0002",
    category: "Laptop",
    brand: "HP",
    model: "EliteBook 840 G8",
    processor: "Intel Core i5",
    generation: "11th Gen",
    ram: "8GB",
    storage: "256GB SSD",
    speed: "2.4GHz",
    screenType: "Non-Touch",
    status: "Ok",
    batchId: "CNT1-TTL-26-0001",
    shipmentId: "CNT1",
    listNumber: "LIST-A",
    source: "scan",
  },
  {
    assetId: "CNT1-TTL-26-0003",
    category: "Laptop",
    brand: "Dell",
    model: "Latitude 5420",
    processor: "Intel Core i7",
    generation: "11th Gen",
    ram: "16GB",
    storage: "512GB SSD",
    speed: "2.6GHz",
    screenType: "Touch Screen",
    status: "Faulty",
    batchId: "CNT1-TTL-26-0002",
    shipmentId: "CNT1",
    listNumber: "LIST-A",
    source: "scan",
  },
  {
    assetId: "CNT1-TTL-26-0004",
    category: "Desktop",
    brand: "HP",
    model: "ProDesk 400 G7 SFF",
    processor: "Intel Core i7",
    generation: "10th Gen",
    ram: "16GB",
    storage: "256GB SSD",
    speed: "2.3GHz",
    screenType: "",
    status: "Ok",
    batchId: "CNT1-TTL-26-0003",
    shipmentId: "CNT1",
    listNumber: "LIST-B",
    source: "scan",
  },
  {
    assetId: "CNT1-TTL-26-0005",
    category: "Desktop",
    brand: "HP",
    model: "ProDesk 400 G7 SFF",
    processor: "Intel Core i7",
    generation: "10th Gen",
    ram: "16GB",
    storage: "256GB SSD",
    speed: "2.3GHz",
    screenType: "",
    status: "Ok",
    batchId: "CNT1-TTL-26-0003",
    shipmentId: "CNT1",
    listNumber: "LIST-B",
    source: "scan",
  },
  {
    assetId: "CNT2-TTL-26-0001",
    category: "Laptop",
    brand: "Lenovo",
    model: "ThinkPad E14",
    processor: "Intel Core i5",
    generation: "10th Gen",
    ram: "8GB",
    storage: "256GB SSD",
    speed: "2.3GHz",
    screenType: "Non-Touch",
    status: "Ok",
    batchId: "CNT2-TTL-26-0001",
    shipmentId: "CNT2",
    listNumber: "LIST-B",
    source: "scan",
  },
  {
    assetId: "CNT2-TTL-26-0002",
    category: "Laptop",
    brand: "Lenovo",
    model: "ThinkPad E14",
    processor: "Intel Core i5",
    generation: "10th Gen",
    ram: "8GB",
    storage: "256GB SSD",
    speed: "2.3GHz",
    screenType: "Non-Touch",
    status: "Faulty",
    batchId: "CNT2-TTL-26-0001",
    shipmentId: "CNT2",
    listNumber: "LIST-B",
    source: "scan",
  },
  {
    assetId: "ASH1-MWS-26-0001",
    category: "Laptop",
    brand: "Lenovo",
    model: "ThinkPad X1 Carbon",
    processor: "Intel Core i7",
    generation: "12th Gen",
    ram: "16GB",
    storage: "512GB SSD",
    speed: "2.1GHz",
    screenType: "Touch Screen",
    status: "Ok",
    batchId: "ASH1-MWS-26-0001",
    shipmentId: "ASH1",
    listNumber: "BATCH-001",
    source: "scan",
  },
  {
    assetId: "ASH1-MWS-26-0002",
    category: "Laptop",
    brand: "Lenovo",
    model: "ThinkPad X1 Carbon",
    processor: "Intel Core i7",
    generation: "12th Gen",
    ram: "16GB",
    storage: "512GB SSD",
    speed: "2.1GHz",
    screenType: "Touch Screen",
    status: "Ok",
    batchId: "ASH1-MWS-26-0001",
    shipmentId: "ASH1",
    listNumber: "BATCH-001",
    source: "scan",
  },
];

// Completed Stock Out transaction history — keyed by invoiceNumber
export const mockStockOutTransactions: StockOutTransaction[] = [
  {
    invoiceNumber: "INV-2026-001",
    customerId: 1,
    customerName: "John Okafor",
    customerEmail: "johnokafor@gmail.com",
    customerPhone: "08034567890",
    customerLocation: "Lagos",
    notes: "",
    date: "20/06/2026",
    processedBy: "Admin",
    totalItems: 2,
    items: [
      {
        assetId: "CNT3-MWS-26-0001",
        category: "Laptop",
        brand: "Dell",
        model: "Latitude 7420",
        processor: "Intel Core i7",
        generation: "11th Gen",
        ram: "16GB",
        storage: "512GB SSD",
        speed: "2.8GHz",
        screenType: "Non-Touch",
        status: "Ok",
        batchId: "CNT3-MWS-26-0001",
        shipmentId: "CNT3",
        listNumber: "LIST-C",
        source: "scan",
      },
      {
        assetId: "CNT3-MWS-26-0002",
        category: "Desktop",
        brand: "HP",
        model: "EliteDesk 800 G6",
        processor: "Intel Core i5",
        generation: "10th Gen",
        ram: "8GB",
        storage: "256GB SSD",
        speed: "3.0GHz",
        screenType: "",
        status: "Ok",
        batchId: "CNT3-MWS-26-0001",
        shipmentId: "CNT3",
        listNumber: "LIST-C",
        source: "scan",
      },
    ],
  },
  {
    invoiceNumber: "INV-2026-002",
    customerId: 2,
    customerName: "Mary Uche",
    customerEmail: "maryuche@gmail.com",
    customerPhone: "08123456789",
    customerLocation: "Abuja",
    notes: "Urgent delivery requested",
    date: "22/06/2026",
    processedBy: "Admin",
    totalItems: 1,
    items: [
      {
        assetId: "CNT3-MWS-26-0003",
        category: "LCD",
        brand: "LG",
        model: "27UK850-W",
        processor: "",
        generation: "",
        ram: "",
        storage: "",
        speed: "",
        screenType: "",
        status: "Faulty",
        batchId: "CNT3-MWS-26-0002",
        shipmentId: "CNT3",
        listNumber: "OFFICE-ITEMS",
        source: "list-number",
      },
    ],
  },
];
