// ─── Stock Out — mock data ─────────────────────────────────────────────────────
//
// The invoice number is the unique identifier for each transaction.
// No system-generated transaction ID is used.
//
// BACKEND INTEGRATION SEAM:
//   Replace with GET /stock-out — list of all completed transactions.
//   The inventory lookup (asset scan validation) will come from
//   GET /inventory/:assetId — not hardcoded here.

import type { StockOutTransaction, ScannedItem } from "./stockOutTypes";

// Mock inventory pool — represents items available for scanning during Stock Out.
// BACKEND INTEGRATION SEAM: GET /inventory?status=Ok,Faulty
export const mockInventoryPool: ScannedItem[] = [
  {
    assetId: "CNT1-TTL-26-0001",
    category: "Laptop",
    brand: "HP",
    model: "EliteBook 840 G8",
    processor: "Intel Core i5",
    generation: "11th Gen",
    ram: "8GB",
    storage: "256GB SSD",
    speed: "2.4GHz",
    screenType: "Non-Touch",
    status: "Ok",
    batchId: "BCH-8F3A91C2",
    shipmentId: "CNT1",
  },
  {
    assetId: "CNT1-TTL-26-0002",
    category: "Laptop",
    brand: "HP",
    model: "EliteBook 840 G8",
    processor: "Intel Core i5",
    generation: "11th Gen",
    ram: "8GB",
    storage: "256GB SSD",
    speed: "2.4GHz",
    screenType: "Non-Touch",
    status: "Ok",
    batchId: "BCH-8F3A91C2",
    shipmentId: "CNT1",
  },
  {
    assetId: "CNT1-TTL-26-0003",
    category: "Laptop",
    brand: "Dell",
    model: "Latitude 5420",
    processor: "Intel Core i7",
    generation: "11th Gen",
    ram: "16GB",
    storage: "512GB SSD",
    speed: "2.6GHz",
    screenType: "Touch Screen",
    status: "Faulty",
    batchId: "BCH-8F3A91C2",
    shipmentId: "CNT1",
  },
  {
    assetId: "CNT1-TTL-26-0004",
    category: "Desktop",
    brand: "HP",
    model: "ProDesk 400 G7 SFF",
    processor: "Intel Core i7",
    generation: "10th Gen",
    ram: "16GB",
    storage: "256GB SSD",
    speed: "2.3GHz",
    screenType: "",
    status: "Ok",
    batchId: "BCH-A72D1E4F",
    shipmentId: "CNT1",
  },
  {
    assetId: "CNT1-TTL-26-0005",
    category: "Desktop",
    brand: "HP",
    model: "ProDesk 400 G7 SFF",
    processor: "Intel Core i7",
    generation: "10th Gen",
    ram: "16GB",
    storage: "256GB SSD",
    speed: "2.3GHz",
    screenType: "",
    status: "Ok",
    batchId: "BCH-A72D1E4F",
    shipmentId: "CNT1",
  },
  {
    assetId: "CNT2-TTL-26-0001",
    category: "Laptop",
    brand: "Lenovo",
    model: "ThinkPad E14",
    processor: "Intel Core i5",
    generation: "10th Gen",
    ram: "8GB",
    storage: "256GB SSD",
    speed: "2.3GHz",
    screenType: "Non-Touch",
    status: "Ok",
    batchId: "BCH-1A9F33B7",
    shipmentId: "CNT2",
  },
  {
    assetId: "CNT2-TTL-26-0002",
    category: "Laptop",
    brand: "Lenovo",
    model: "ThinkPad E14",
    processor: "Intel Core i5",
    generation: "10th Gen",
    ram: "8GB",
    storage: "256GB SSD",
    speed: "2.3GHz",
    screenType: "Non-Touch",
    status: "Faulty",
    batchId: "BCH-1A9F33B7",
    shipmentId: "CNT2",
  },
  {
    assetId: "ASH1-MWS-26-0001",
    category: "Laptop",
    brand: "Lenovo",
    model: "ThinkPad X1 Carbon",
    processor: "Intel Core i7",
    generation: "12th Gen",
    ram: "16GB",
    storage: "512GB SSD",
    speed: "2.1GHz",
    screenType: "Touch Screen",
    status: "Ok",
    batchId: "BCH-5E4F3A2B",
    shipmentId: "ASH1",
  },
  {
    assetId: "ASH1-MWS-26-0002",
    category: "Laptop",
    brand: "Lenovo",
    model: "ThinkPad X1 Carbon",
    processor: "Intel Core i7",
    generation: "12th Gen",
    ram: "16GB",
    storage: "512GB SSD",
    speed: "2.1GHz",
    screenType: "Touch Screen",
    status: "Ok",
    batchId: "BCH-5E4F3A2B",
    shipmentId: "ASH1",
  },
];

// Completed Stock Out transaction history — keyed by invoiceNumber
export const mockStockOutTransactions: StockOutTransaction[] = [
  {
    invoiceNumber: "INV-2026-001",
    customerId: 1,
    customerName: "John Okafor",
    customerEmail: "johnokafor@gmail.com",
    customerPhone: "08034567890",
    customerLocation: "Lagos",
    notes: "",
    date: "20/06/2026",
    processedBy: "Admin",
    totalItems: 2,
    items: [
      {
        assetId: "CNT3-MWS-26-0001",
        category: "Laptop",
        brand: "Dell",
        model: "Latitude 7420",
        processor: "Intel Core i7",
        generation: "11th Gen",
        ram: "16GB",
        storage: "512GB SSD",
        speed: "2.8GHz",
        screenType: "Non-Touch",
        status: "Ok",
        batchId: "BCH-C3D2E1F0",
        shipmentId: "CNT3",
      },
      {
        assetId: "CNT3-MWS-26-0002",
        category: "Desktop",
        brand: "HP",
        model: "EliteDesk 800 G6",
        processor: "Intel Core i5",
        generation: "10th Gen",
        ram: "8GB",
        storage: "256GB SSD",
        speed: "3.0GHz",
        screenType: "",
        status: "Ok",
        batchId: "BCH-C3D2E1F0",
        shipmentId: "CNT3",
      },
    ],
  },
  {
    invoiceNumber: "INV-2026-002",
    customerId: 2,
    customerName: "Mary Uche",
    customerEmail: "maryuche@gmail.com",
    customerPhone: "08123456789",
    customerLocation: "Abuja",
    notes: "Urgent delivery requested",
    date: "22/06/2026",
    processedBy: "Admin",
    totalItems: 1,
    items: [
      {
        assetId: "CNT3-MWS-26-0003",
        category: "LCD",
        brand: "LG",
        model: "27UK850-W",
        processor: "",
        generation: "",
        ram: "",
        storage: "",
        speed: "",
        screenType: "",
        status: "Faulty",
        batchId: "BCH-C3D2E1F0",
        shipmentId: "CNT3",
      },
    ],
  },
];