import type { Shipment } from "./shipmentTypes";

// NOTE FOR BACKEND INTEGRATION: okCount, faultyCount, issuedCount are
// derived by counting inventory records for this shipmentId by status.
// Backend: SELECT status, COUNT(*) FROM inventory WHERE shipment_id = $1 GROUP BY status
const mockShipments: Shipment[] = [
  {
    id: 1,
    shipmentId: "CNT1",
    shipmentName: "Container 1",
    vendor: "TTL",
    itemsSent: 560,
    itemsReceived: 560,
    okCount: 536,
    faultyCount: 20,
    issuedCount: 4,
    shipmentReceivedDate: "20/05/2024",
    status: "Complete",
  },
  {
    id: 2,
    shipmentId: "CNT2",
    shipmentName: "Container 2",
    vendor: "TTL",
    itemsSent: 430,
    itemsReceived: 418,
    okCount: 400,
    faultyCount: 15,
    issuedCount: 3,
    shipmentReceivedDate: "22/05/2024",
    status: "In Progress",
  },
  {
    id: 3,
    shipmentId: "CNT3",
    shipmentName: "Container 3",
    vendor: "MWS",
    itemsSent: 620,
    itemsReceived: 612,
    okCount: 590,
    faultyCount: 18,
    issuedCount: 4,
    shipmentReceivedDate: "19/05/2024",
    status: "In Progress",
  },
  {
    id: 4,
    shipmentId: "ASH1",
    shipmentName: "Air Shipment 1",
    vendor: "MWS",
    itemsSent: 300,
    itemsReceived: 298,
    okCount: 280,
    faultyCount: 12,
    issuedCount: 6,
    shipmentReceivedDate: "18/05/2024",
    status: "In Progress",
  },
  {
    id: 5,
    shipmentId: "CONT4",
    shipmentName: "Container 4",
    vendor: "TTL",
    itemsSent: 210,
    itemsReceived: 209,
    okCount: 200,
    faultyCount: 7,
    issuedCount: 2,
    shipmentReceivedDate: "17/05/2024",
    status: "In Progress",
  },
  {
    id: 6,
    shipmentId: "ASH2",
    shipmentName: "Air Shipment 2",
    vendor: "TTL",
    itemsSent: 815,
    itemsReceived: 803,
    okCount: 770,
    faultyCount: 25,
    issuedCount: 8,
    shipmentReceivedDate: "16/05/2026",
    status: "In Progress",
  },
  {
    id: 7,
    shipmentId: "CNT4",
    shipmentName: "Container 4",
    vendor: "TTL",
    itemsSent: 450,
    itemsReceived: 0,
    okCount: 0,
    faultyCount: 0,
    issuedCount: 0,
    shipmentReceivedDate: "12/06/2026",
    status: "Pending",
  },
];

export default mockShipments;