import type { FaultyStockItem } from "./faultyStockTypes";

// 12 assets currently marked Faulty. The first 5 (LIST-A-26-0005,
// LIST-B-26-0003, BATCH-001-26-0001, LIST-A-26-0008, LIST-A-26-0010) mirror
// the Faulty records already seeded in mockDatabase.ts — same asset IDs,
// same fault types, same traceability fields. The remaining 7 extend the
// picture with an LCD unit, more multi-fault items, and dates running into
// June 2026.
export const mockFaultyStock: FaultyStockItem[] = [
  {
    assetId: "LIST-A-26-0005",
    category: "Laptop",
    brand: "HP",
    model: "EliteBook 840 G8",
    processor: "Intel Core i5",
    generation: "11th Gen",
    ram: "8GB",
    storage: "256GB SSD",
    speed: "2.40GHz",
    screenType: "Non-Touch",
    faultTypes: ["LCD Spot"],
    dateMarkedFaulty: "05/05/2026 11:20 AM",
    adjustedBy: "Tunde Bakare",
    shipmentId: "CNT1",
    batchId: "CNT1-TTL-26-0002",
    listNumber: "LIST-A",
    notes: "Small dead-pixel cluster near top-left.",
  },
  {
    assetId: "LIST-B-26-0003",
    category: "Desktop",
    brand: "Lenovo",
    model: "ThinkCentre M720",
    processor: "Intel Core i5",
    generation: "10th Gen",
    ram: "8GB",
    storage: "256GB SSD",
    speed: "2.90GHz",
    screenType: "Non-Touch",
    faultTypes: ["Dead Board"],
    dateMarkedFaulty: "08/05/2026 02:05 PM",
    adjustedBy: "admin",
    shipmentId: "CNT2",
    batchId: "CNT2-TTL-26-0001",
    listNumber: "LIST-B",
    notes: "Does not power on at all.",
  },
  {
    assetId: "BATCH-001-26-0001",
    category: "All In One",
    brand: "Apple",
    model: "iMac 24-inch",
    processor: "Apple M1",
    generation: "",
    ram: "16GB",
    storage: "512GB SSD",
    speed: "",
    screenType: "Non-Touch",
    faultTypes: ["No Display"],
    dateMarkedFaulty: "12/05/2026 10:24 AM",
    adjustedBy: "Tunde Bakare",
    shipmentId: "CNT2",
    batchId: "CNT2-MWS-26-0001",
    listNumber: "BATCH-001",
    notes: "Screen stays black even with the power light on.",
  },
  {
    assetId: "LIST-A-26-0008",
    category: "Laptop",
    brand: "HP",
    model: "ProBook 450 G8",
    processor: "Intel Core i5",
    generation: "11th Gen",
    ram: "8GB",
    storage: "256GB SSD",
    speed: "2.50GHz",
    screenType: "Non-Touch",
    faultTypes: ["Keyboard Fault"],
    dateMarkedFaulty: "22/05/2026 09:40 AM",
    adjustedBy: "admin",
    shipmentId: "ASH1",
    batchId: "ASH1-ARC-26-0001",
    listNumber: "LIST-A",
    notes: "",
  },
  {
    assetId: "LIST-A-26-0010",
    category: "Desktop",
    brand: "HP",
    model: "ProDesk 400 G6",
    processor: "Intel Core i5",
    generation: "10th Gen",
    ram: "8GB",
    storage: "256GB SSD",
    speed: "3.20GHz",
    screenType: "Non-Touch",
    faultTypes: ["HDD Failure"],
    dateMarkedFaulty: "22/05/2026 09:40 AM",
    adjustedBy: "admin",
    shipmentId: "ASH1",
    batchId: "ASH1-ARC-26-0001",
    listNumber: "LIST-A",
    notes: "Clicking noise from drive; failed self-test.",
  },
  {
    assetId: "OFFICE-ITEMS-26-0004",
    category: "LCD",
    brand: "Dell",
    model: "P2422H",
    processor: "",
    generation: "",
    ram: "",
    storage: "",
    speed: "",
    screenType: "Non-Touch",
    faultTypes: ["No Display"],
    dateMarkedFaulty: "02/06/2026 10:15 AM",
    adjustedBy: "admin",
    shipmentId: "ASH1",
    batchId: "ASH1-MWS-26-0002",
    listNumber: "OFFICE-ITEMS",
    notes: "Panel shows no image; backlight not lit.",
  },
  {
    assetId: "LIST-B-26-0009",
    category: "Laptop",
    brand: "Dell",
    model: "Latitude 5420",
    processor: "Intel Core i7",
    generation: "11th Gen",
    ram: "16GB",
    storage: "512GB SSD",
    speed: "2.60GHz",
    screenType: "Touch Screen",
    faultTypes: ["Battery Fault", "Overheating"],
    dateMarkedFaulty: "05/06/2026 03:40 PM",
    adjustedBy: "Tunde Bakare",
    shipmentId: "CNT1",
    batchId: "CNT1-TTL-26-0003",
    listNumber: "LIST-B",
    notes: "Battery drains fast and device gets hot under load.",
  },
  {
    assetId: "LIST-A-26-0011",
    category: "Desktop",
    brand: "Lenovo",
    model: "ThinkCentre M720",
    processor: "Intel Core i5",
    generation: "10th Gen",
    ram: "8GB",
    storage: "256GB SSD",
    speed: "2.90GHz",
    screenType: "Non-Touch",
    faultTypes: ["No Power"],
    dateMarkedFaulty: "12/06/2026 09:00 AM",
    adjustedBy: "admin",
    shipmentId: "CNT2",
    batchId: "CNT2-TTL-26-0002",
    listNumber: "LIST-A",
    notes: "Unit does not switch on; PSU suspected faulty.",
  },
  {
    assetId: "LIST-B-26-0010",
    category: "Laptop",
    brand: "HP",
    model: "EliteBook 840 G8",
    processor: "Intel Core i5",
    generation: "11th Gen",
    ram: "8GB",
    storage: "256GB SSD",
    speed: "2.40GHz",
    screenType: "Non-Touch",
    faultTypes: ["Touchpad Fault", "Keyboard Fault"],
    dateMarkedFaulty: "15/06/2026 01:25 PM",
    adjustedBy: "Tunde Bakare",
    shipmentId: "CNT3",
    batchId: "CNT3-ARC-26-0002",
    listNumber: "LIST-B",
    notes: "Touchpad unresponsive; several keys sticking.",
  },
  {
    assetId: "OFFICE-ITEMS-26-0005",
    category: "LCD",
    brand: "HP",
    model: "E24 G5",
    processor: "",
    generation: "",
    ram: "",
    storage: "",
    speed: "",
    screenType: "Non-Touch",
    faultTypes: ["Screen Fault"],
    dateMarkedFaulty: "20/06/2026 11:50 AM",
    adjustedBy: "admin",
    shipmentId: "ASH1",
    batchId: "ASH1-MWS-26-0002",
    listNumber: "OFFICE-ITEMS",
    notes: "Flickering display with faint vertical lines.",
  },
  {
    assetId: "LIST-A-26-0012",
    category: "All In One",
    brand: "Dell",
    model: "OptiPlex 7400 AIO",
    processor: "Intel Core i5",
    generation: "12th Gen",
    ram: "8GB",
    storage: "256GB SSD",
    speed: "2.70GHz",
    screenType: "Touch Screen",
    faultTypes: ["RAM Fault", "Overheating", "No Display"],
    dateMarkedFaulty: "24/06/2026 04:05 PM",
    adjustedBy: "Tunde Bakare",
    shipmentId: "CNT1",
    batchId: "CNT1-TTL-26-0003",
    listNumber: "LIST-A",
    notes: "Random shutdowns; runs hot; screen occasionally blanks out.",
  },
  {
    assetId: "LIST-B-26-0011",
    category: "Laptop",
    brand: "Lenovo",
    model: "ThinkPad T14",
    processor: "Intel Core i7",
    generation: "12th Gen",
    ram: "16GB",
    storage: "512GB SSD",
    speed: "2.80GHz",
    screenType: "Non-Touch",
    faultTypes: ["HDD Failure"],
    dateMarkedFaulty: "28/06/2026 10:30 AM",
    adjustedBy: "admin",
    shipmentId: "CNT2",
    batchId: "CNT2-TTL-26-0002",
    listNumber: "LIST-B",
    notes: "Drive not detected in BIOS intermittently.",
  },
];

export default mockFaultyStock;
