import type { InventoryAsset } from "./databaseTypes";

// 25 assets spanning 4 shipments (CNT1, CNT2, ASH1, CNT3) and 3 vendors
// (TTL, MWS, ARC) — 15 Ok, 5 Faulty, 5 Issued; 4 "provided" asset IDs
// (vendor-tagged Apple hardware), the rest system-generated.
export const mockDatabase: InventoryAsset[] = [
  {
    assetId: "LIST-A-26-0001",
    assetIdSource: "generated",
    listNumber: "LIST-A",
    batchId: "CNT1-TTL-26-0001",
    shipmentId: "CNT1",
    vendorId: "TTL",
    category: "Laptop",
    brand: "HP",
    model: "EliteBook 840 G8",
    processor: "Intel Core i5",
    generation: "11th Gen",
    ram: "8GB",
    storage: "256GB SSD",
    speed: "2.40GHz",
    screenType: "Non-Touch",
    status: "Ok",
    importedBy: "admin",
    importDate: "03/05/2026 09:10 AM",
    faultTypes: [],
    notes: "",
  },
  {
    assetId: "LIST-A-26-0002",
    assetIdSource: "generated",
    listNumber: "LIST-A",
    batchId: "CNT1-TTL-26-0001",
    shipmentId: "CNT1",
    vendorId: "TTL",
    category: "Laptop",
    brand: "HP",
    model: "EliteBook 840 G8",
    processor: "Intel Core i5",
    generation: "11th Gen",
    ram: "8GB",
    storage: "256GB SSD",
    speed: "2.40GHz",
    screenType: "Non-Touch",
    status: "Ok",
    importedBy: "admin",
    importDate: "03/05/2026 09:10 AM",
    faultTypes: [],
    notes: "",
  },
  {
    assetId: "LIST-A-26-0003",
    assetIdSource: "generated",
    listNumber: "LIST-A",
    batchId: "CNT1-TTL-26-0001",
    shipmentId: "CNT1",
    vendorId: "TTL",
    category: "Desktop",
    brand: "Dell",
    model: "OptiPlex 7090",
    processor: "Intel Core i7",
    generation: "11th Gen",
    ram: "16GB",
    storage: "512GB SSD",
    speed: "3.00GHz",
    screenType: "Non-Touch",
    status: "Ok",
    importedBy: "admin",
    importDate: "03/05/2026 09:12 AM",
    faultTypes: [],
    notes: "",
  },
  {
    assetId: "LIST-A-26-0004",
    assetIdSource: "generated",
    listNumber: "LIST-A",
    batchId: "CNT1-TTL-26-0001",
    shipmentId: "CNT1",
    vendorId: "TTL",
    category: "Desktop",
    brand: "Dell",
    model: "OptiPlex 7090",
    processor: "Intel Core i7",
    generation: "11th Gen",
    ram: "16GB",
    storage: "512GB SSD",
    speed: "3.00GHz",
    screenType: "Non-Touch",
    status: "Issued",
    importedBy: "admin",
    importDate: "03/05/2026 09:12 AM",
    faultTypes: [],
    notes: "",
  },
  {
    assetId: "LIST-A-26-0005",
    assetIdSource: "generated",
    listNumber: "LIST-A",
    batchId: "CNT1-TTL-26-0002",
    shipmentId: "CNT1",
    vendorId: "TTL",
    category: "Laptop",
    brand: "HP",
    model: "EliteBook 840 G8",
    processor: "Intel Core i5",
    generation: "11th Gen",
    ram: "8GB",
    storage: "256GB SSD",
    speed: "2.40GHz",
    screenType: "Non-Touch",
    status: "Faulty",
    importedBy: "Tunde Bakare",
    importDate: "05/05/2026 11:20 AM",
    faultTypes: ["LCD Spot"],
    notes: "Small dead-pixel cluster near top-left.",
  },
  {
    assetId: "LIST-A-26-0006",
    assetIdSource: "generated",
    listNumber: "LIST-A",
    batchId: "CNT1-TTL-26-0002",
    shipmentId: "CNT1",
    vendorId: "TTL",
    category: "Laptop",
    brand: "Dell",
    model: "Latitude 5420",
    processor: "Intel Core i7",
    generation: "11th Gen",
    ram: "16GB",
    storage: "512GB SSD",
    speed: "2.60GHz",
    screenType: "Touch Screen",
    status: "Ok",
    importedBy: "Tunde Bakare",
    importDate: "05/05/2026 11:20 AM",
    faultTypes: [],
    notes: "",
  },
  {
    assetId: "LIST-A-26-0007",
    assetIdSource: "generated",
    listNumber: "LIST-A",
    batchId: "CNT1-TTL-26-0002",
    shipmentId: "CNT1",
    vendorId: "TTL",
    category: "Laptop",
    brand: "Dell",
    model: "Latitude 5420",
    processor: "Intel Core i7",
    generation: "11th Gen",
    ram: "16GB",
    storage: "512GB SSD",
    speed: "2.60GHz",
    screenType: "Touch Screen",
    status: "Ok",
    importedBy: "Tunde Bakare",
    importDate: "05/05/2026 11:20 AM",
    faultTypes: [],
    notes: "",
  },
  {
    assetId: "LIST-B-26-0001",
    assetIdSource: "generated",
    listNumber: "LIST-B",
    batchId: "CNT2-TTL-26-0001",
    shipmentId: "CNT2",
    vendorId: "TTL",
    category: "Laptop",
    brand: "Lenovo",
    model: "ThinkPad T14",
    processor: "Intel Core i7",
    generation: "12th Gen",
    ram: "16GB",
    storage: "512GB SSD",
    speed: "2.80GHz",
    screenType: "Non-Touch",
    status: "Ok",
    importedBy: "admin",
    importDate: "08/05/2026 02:00 PM",
    faultTypes: [],
    notes: "",
  },
  {
    assetId: "LIST-B-26-0002",
    assetIdSource: "generated",
    listNumber: "LIST-B",
    batchId: "CNT2-TTL-26-0001",
    shipmentId: "CNT2",
    vendorId: "TTL",
    category: "Laptop",
    brand: "Lenovo",
    model: "ThinkPad T14",
    processor: "Intel Core i7",
    generation: "12th Gen",
    ram: "16GB",
    storage: "512GB SSD",
    speed: "2.80GHz",
    screenType: "Non-Touch",
    status: "Issued",
    importedBy: "admin",
    importDate: "08/05/2026 02:00 PM",
    faultTypes: [],
    notes: "",
  },
  {
    assetId: "LIST-B-26-0003",
    assetIdSource: "generated",
    listNumber: "LIST-B",
    batchId: "CNT2-TTL-26-0001",
    shipmentId: "CNT2",
    vendorId: "TTL",
    category: "Desktop",
    brand: "Lenovo",
    model: "ThinkCentre M720",
    processor: "Intel Core i5",
    generation: "10th Gen",
    ram: "8GB",
    storage: "256GB SSD",
    speed: "2.90GHz",
    screenType: "Non-Touch",
    status: "Faulty",
    importedBy: "admin",
    importDate: "08/05/2026 02:05 PM",
    faultTypes: ["Dead Board"],
    notes: "Does not power on at all.",
  },
  {
    assetId: "006704358",
    assetIdSource: "provided",
    listNumber: "BATCH-001",
    batchId: "CNT2-MWS-26-0001",
    shipmentId: "CNT2",
    vendorId: "MWS",
    category: "All In One",
    brand: "Apple",
    model: "iMac 24-inch",
    processor: "Apple M1",
    generation: "",
    ram: "8GB",
    storage: "256GB SSD",
    speed: "",
    screenType: "Non-Touch",
    status: "Ok",
    importedBy: "Tunde Bakare",
    importDate: "12/05/2026 10:24 AM",
    faultTypes: [],
    notes: "",
  },
  {
    assetId: "006704359",
    assetIdSource: "provided",
    listNumber: "BATCH-001",
    batchId: "CNT2-MWS-26-0001",
    shipmentId: "CNT2",
    vendorId: "MWS",
    category: "All In One",
    brand: "Apple",
    model: "iMac 24-inch",
    processor: "Apple M1",
    generation: "",
    ram: "8GB",
    storage: "256GB SSD",
    speed: "",
    screenType: "Non-Touch",
    status: "Ok",
    importedBy: "Tunde Bakare",
    importDate: "12/05/2026 10:24 AM",
    faultTypes: [],
    notes: "",
  },
  {
    assetId: "BATCH-001-26-0001",
    assetIdSource: "generated",
    listNumber: "BATCH-001",
    batchId: "CNT2-MWS-26-0001",
    shipmentId: "CNT2",
    vendorId: "MWS",
    category: "All In One",
    brand: "Apple",
    model: "iMac 24-inch",
    processor: "Apple M1",
    generation: "",
    ram: "16GB",
    storage: "512GB SSD",
    speed: "",
    screenType: "Non-Touch",
    status: "Faulty",
    importedBy: "Tunde Bakare",
    importDate: "12/05/2026 10:24 AM",
    faultTypes: ["No Display"],
    notes: "Screen stays black even with the power light on.",
  },
  {
    assetId: "OFFICE-ITEMS-26-0001",
    assetIdSource: "generated",
    listNumber: "OFFICE-ITEMS",
    batchId: "ASH1-MWS-26-0001",
    shipmentId: "ASH1",
    vendorId: "MWS",
    category: "LCD",
    brand: "Dell",
    model: "P2422H",
    processor: "",
    generation: "",
    ram: "",
    storage: "",
    speed: "",
    screenType: "Non-Touch",
    status: "Ok",
    importedBy: "admin",
    importDate: "18/05/2026 03:15 PM",
    faultTypes: [],
    notes: "",
  },
  {
    assetId: "OFFICE-ITEMS-26-0002",
    assetIdSource: "generated",
    listNumber: "OFFICE-ITEMS",
    batchId: "ASH1-MWS-26-0001",
    shipmentId: "ASH1",
    vendorId: "MWS",
    category: "LCD",
    brand: "Dell",
    model: "P2422H",
    processor: "",
    generation: "",
    ram: "",
    storage: "",
    speed: "",
    screenType: "Non-Touch",
    status: "Ok",
    importedBy: "admin",
    importDate: "18/05/2026 03:15 PM",
    faultTypes: [],
    notes: "",
  },
  {
    assetId: "OFFICE-ITEMS-26-0003",
    assetIdSource: "generated",
    listNumber: "OFFICE-ITEMS",
    batchId: "ASH1-MWS-26-0001",
    shipmentId: "ASH1",
    vendorId: "MWS",
    category: "LCD",
    brand: "HP",
    model: "E24 G5",
    processor: "",
    generation: "",
    ram: "",
    storage: "",
    speed: "",
    screenType: "Non-Touch",
    status: "Issued",
    importedBy: "admin",
    importDate: "18/05/2026 03:15 PM",
    faultTypes: [],
    notes: "",
  },
  {
    assetId: "LIST-A-26-0008",
    assetIdSource: "generated",
    listNumber: "LIST-A",
    batchId: "ASH1-ARC-26-0001",
    shipmentId: "ASH1",
    vendorId: "ARC",
    category: "Laptop",
    brand: "HP",
    model: "ProBook 450 G8",
    processor: "Intel Core i5",
    generation: "11th Gen",
    ram: "8GB",
    storage: "256GB SSD",
    speed: "2.50GHz",
    screenType: "Non-Touch",
    status: "Faulty",
    importedBy: "admin",
    importDate: "22/05/2026 09:40 AM",
    faultTypes: ["Keyboard Fault"],
    notes: "",
  },
  {
    assetId: "LIST-A-26-0009",
    assetIdSource: "generated",
    listNumber: "LIST-A",
    batchId: "ASH1-ARC-26-0001",
    shipmentId: "ASH1",
    vendorId: "ARC",
    category: "Desktop",
    brand: "HP",
    model: "ProDesk 400 G6",
    processor: "Intel Core i5",
    generation: "10th Gen",
    ram: "8GB",
    storage: "256GB SSD",
    speed: "3.20GHz",
    screenType: "Non-Touch",
    status: "Ok",
    importedBy: "admin",
    importDate: "22/05/2026 09:40 AM",
    faultTypes: [],
    notes: "",
  },
  {
    assetId: "LIST-A-26-0010",
    assetIdSource: "generated",
    listNumber: "LIST-A",
    batchId: "ASH1-ARC-26-0001",
    shipmentId: "ASH1",
    vendorId: "ARC",
    category: "Desktop",
    brand: "HP",
    model: "ProDesk 400 G6",
    processor: "Intel Core i5",
    generation: "10th Gen",
    ram: "8GB",
    storage: "256GB SSD",
    speed: "3.20GHz",
    screenType: "Non-Touch",
    status: "Faulty",
    importedBy: "admin",
    importDate: "22/05/2026 09:40 AM",
    faultTypes: ["HDD Failure"],
    notes: "Clicking noise from drive; failed self-test.",
  },
  {
    assetId: "LIST-B-26-0004",
    assetIdSource: "generated",
    listNumber: "LIST-B",
    batchId: "CNT3-ARC-26-0001",
    shipmentId: "CNT3",
    vendorId: "ARC",
    category: "Laptop",
    brand: "Lenovo",
    model: "ThinkPad E14",
    processor: "Intel Core i5",
    generation: "11th Gen",
    ram: "8GB",
    storage: "256GB SSD",
    speed: "2.60GHz",
    screenType: "Non-Touch",
    status: "Ok",
    importedBy: "Tunde Bakare",
    importDate: "29/05/2026 01:00 PM",
    faultTypes: [],
    notes: "",
  },
  {
    assetId: "LIST-B-26-0005",
    assetIdSource: "generated",
    listNumber: "LIST-B",
    batchId: "CNT3-ARC-26-0001",
    shipmentId: "CNT3",
    vendorId: "ARC",
    category: "Laptop",
    brand: "Lenovo",
    model: "ThinkPad E14",
    processor: "Intel Core i5",
    generation: "11th Gen",
    ram: "8GB",
    storage: "256GB SSD",
    speed: "2.60GHz",
    screenType: "Non-Touch",
    status: "Ok",
    importedBy: "Tunde Bakare",
    importDate: "29/05/2026 01:00 PM",
    faultTypes: [],
    notes: "",
  },
  {
    assetId: "LIST-B-26-0006",
    assetIdSource: "generated",
    listNumber: "LIST-B",
    batchId: "CNT3-ARC-26-0001",
    shipmentId: "CNT3",
    vendorId: "ARC",
    category: "Desktop",
    brand: "Dell",
    model: "OptiPlex 5090",
    processor: "Intel Core i5",
    generation: "11th Gen",
    ram: "8GB",
    storage: "256GB SSD",
    speed: "2.90GHz",
    screenType: "Non-Touch",
    status: "Issued",
    importedBy: "Tunde Bakare",
    importDate: "29/05/2026 01:00 PM",
    faultTypes: [],
    notes: "",
  },
  {
    assetId: "006704412",
    assetIdSource: "provided",
    listNumber: "BATCH-001",
    batchId: "CNT3-TTL-26-0001",
    shipmentId: "CNT3",
    vendorId: "TTL",
    category: "Laptop",
    brand: "Apple",
    model: "MacBook Air M2",
    processor: "Apple M2",
    generation: "",
    ram: "8GB",
    storage: "256GB SSD",
    speed: "",
    screenType: "Non-Touch",
    status: "Ok",
    importedBy: "admin",
    importDate: "07/06/2026 04:10 PM",
    faultTypes: [],
    notes: "",
  },
  {
    assetId: "006704413",
    assetIdSource: "provided",
    listNumber: "BATCH-001",
    batchId: "CNT3-TTL-26-0001",
    shipmentId: "CNT3",
    vendorId: "TTL",
    category: "Laptop",
    brand: "Apple",
    model: "MacBook Air M2",
    processor: "Apple M2",
    generation: "",
    ram: "8GB",
    storage: "256GB SSD",
    speed: "",
    screenType: "Non-Touch",
    status: "Ok",
    importedBy: "admin",
    importDate: "07/06/2026 04:10 PM",
    faultTypes: [],
    notes: "",
  },
  {
    assetId: "LIST-B-26-0007",
    assetIdSource: "generated",
    listNumber: "LIST-B",
    batchId: "CNT3-TTL-26-0001",
    shipmentId: "CNT3",
    vendorId: "TTL",
    category: "Desktop",
    brand: "Dell",
    model: "OptiPlex 5090",
    processor: "Intel Core i5",
    generation: "11th Gen",
    ram: "8GB",
    storage: "256GB SSD",
    speed: "2.90GHz",
    screenType: "Non-Touch",
    status: "Issued",
    importedBy: "admin",
    importDate: "11/06/2026 12:05 PM",
    faultTypes: [],
    notes: "",
  },
];

export default mockDatabase;
