import type { ImportedInventoryItem } from "./ImportedInventoryTypes";

// Mock inventory records already "committed" to the system, spanning multiple
// batches per shipment — CNT1 has 3 separate import sessions (2 manual, 1 csv)
// to demonstrate that View Imported Inventory shows the full history, not
// just the latest session. CNT2 has a single batch with one faulty item to
// exercise the status filter.

export const importedInventory: ImportedInventoryItem[] = [
  // ── CNT1 — Batch 1 (manual entry, oldest) ──────────────────────────────────
  {
    assetId: "CNT1-TTL-26-0001",
    batchId: "BCH-8F3A91C2",
    category: "Laptop",
    condition: "New",
    brand: "HP",
    model: "EliteBook 840 G8",
    processor: "Intel Core i5",
    generation: "11th Gen",
    ram: "8GB",
    storage: "256GB SSD",
    speed: "2.4GHz",
    screenType: "Non-Touch",
    additionalInfo: "",
    status: "Ok",
    source: "manual",
    dateImported: "12/05/2026 10:24 AM",
  },
  {
    assetId: "CNT1-TTL-26-0002",
    batchId: "BCH-8F3A91C2",
    category: "Laptop",
    condition: "New",
    brand: "HP",
    model: "EliteBook 840 G8",
    processor: "Intel Core i5",
    generation: "11th Gen",
    ram: "8GB",
    storage: "256GB SSD",
    speed: "2.4GHz",
    screenType: "Non-Touch",
    additionalInfo: "",
    status: "Ok",
    source: "manual",
    dateImported: "12/05/2026 10:24 AM",
  },
  {
    assetId: "CNT1-TTL-26-0003",
    batchId: "BCH-8F3A91C2",
    category: "Laptop",
    condition: "Refurb",
    brand: "Dell",
    model: "Latitude 5420",
    processor: "Intel Core i7",
    generation: "11th Gen",
    ram: "16GB",
    storage: "512GB SSD",
    speed: "2.6GHz",
    screenType: "Touch Screen",
    additionalInfo: "",
    status: "Faulty",
    source: "manual",
    dateImported: "12/05/2026 10:24 AM",
  },

  // ── CNT1 — Batch 2 (CSV import, a day later) ───────────────────────────────
  {
    assetId: "CNT1-TTL-26-0004",
    batchId: "BCH-A72D1E4F",
    category: "Desktop",
    condition: "New",
    brand: "HP",
    model: "ProDesk 400 G7 SFF",
    processor: "Intel Core i7",
    generation: "10th Gen",
    ram: "16GB",
    storage: "256GB SSD",
    speed: "2.3GHz",
    screenType: "",
    additionalInfo: "",
    status: "Ok",
    source: "csv",
    dateImported: "13/05/2026 09:15 AM",
  },
  {
    assetId: "CNT1-TTL-26-0005",
    batchId: "BCH-A72D1E4F",
    category: "Desktop",
    condition: "New",
    brand: "HP",
    model: "ProDesk 400 G7 SFF",
    processor: "Intel Core i7",
    generation: "10th Gen",
    ram: "16GB",
    storage: "256GB SSD",
    speed: "2.3GHz",
    screenType: "",
    additionalInfo: "",
    status: "Ok",
    source: "csv",
    dateImported: "13/05/2026 09:15 AM",
  },
  {
    assetId: "CNT1-TTL-26-0006",
    batchId: "BCH-A72D1E4F",
    category: "Workstation",
    condition: "New",
    brand: "HP",
    model: "Z2 G8 Tower",
    processor: "Intel Core i7",
    generation: "11th Gen",
    ram: "16GB",
    storage: "512GB SSD",
    speed: "2.8GHz",
    screenType: "",
    additionalInfo: "",
    status: "Ok",
    source: "csv",
    dateImported: "13/05/2026 09:15 AM",
  },

  // ── CNT1 — Batch 3 (manual entry, most recent) ─────────────────────────────
  {
    assetId: "CNT1-TTL-26-0007",
    batchId: "BCH-4B6C90D8",
    category: "LCD",
    condition: "New",
    brand: "Dell",
    model: "P2422H",
    processor: "",
    generation: "",
    ram: "",
    storage: "",
    speed: "",
    screenType: "Non-Touch",
    additionalInfo: "",
    status: "Ok",
    source: "manual",
    dateImported: "14/05/2026 03:40 PM",
  },
  {
    assetId: "CNT1-TTL-26-0008",
    batchId: "BCH-4B6C90D8",
    category: "LCD",
    condition: "New",
    brand: "Dell",
    model: "P2422H",
    processor: "",
    generation: "",
    ram: "",
    storage: "",
    speed: "",
    screenType: "Non-Touch",
    additionalInfo: "",
    status: "Ok",
    source: "manual",
    dateImported: "14/05/2026 03:40 PM",
  },

  // ── CNT2 — Single batch (csv) ───────────────────────────────────────────────
  {
    assetId: "CNT2-TTL-26-0001",
    batchId: "BCH-1A9F33B7",
    category: "Laptop",
    condition: "Used",
    brand: "Lenovo",
    model: "ThinkPad E14",
    processor: "Intel Core i5",
    generation: "10th Gen",
    ram: "8GB",
    storage: "256GB SSD",
    speed: "2.3GHz",
    screenType: "Non-Touch",
    additionalInfo: "",
    status: "Ok",
    source: "csv",
    dateImported: "13/05/2026 11:05 AM",
  },
  {
    assetId: "CNT2-TTL-26-0002",
    batchId: "BCH-1A9F33B7",
    category: "Laptop",
    condition: "Used",
    brand: "Lenovo",
    model: "ThinkPad E14",
    processor: "Intel Core i5",
    generation: "10th Gen",
    ram: "8GB",
    storage: "256GB SSD",
    speed: "2.3GHz",
    screenType: "Non-Touch",
    additionalInfo: "",
    status: "Faulty",
    source: "csv",
    dateImported: "13/05/2026 11:05 AM",
  },

  // ── CNT3 — Single batch (csv, MWS vendor) ──────────────────────────────────
  {
    assetId: "CNT3-MWS-26-0001",
    batchId: "BCH-C3D2E1F0",
    category: "Laptop",
    condition: "Refurb",
    brand: "Dell",
    model: "Latitude 7420",
    processor: "Intel Core i7",
    generation: "11th Gen",
    ram: "16GB",
    storage: "512GB SSD",
    speed: "2.8GHz",
    screenType: "Non-Touch",
    additionalInfo: "",
    status: "Ok",
    source: "csv",
    dateImported: "20/05/2026 08:30 AM",
  },
  {
    assetId: "CNT3-MWS-26-0002",
    batchId: "BCH-C3D2E1F0",
    category: "Desktop",
    condition: "Refurb",
    brand: "HP",
    model: "EliteDesk 800 G6",
    processor: "Intel Core i5",
    generation: "10th Gen",
    ram: "8GB",
    storage: "256GB SSD",
    speed: "3.0GHz",
    screenType: "",
    additionalInfo: "",
    status: "Ok",
    source: "csv",
    dateImported: "20/05/2026 08:30 AM",
  },
  {
    assetId: "CNT3-MWS-26-0003",
    batchId: "BCH-C3D2E1F0",
    category: "LCD",
    condition: "Used",
    brand: "LG",
    model: "27UK850-W",
    processor: "",
    generation: "",
    ram: "",
    storage: "",
    speed: "",
    screenType: "",
    additionalInfo: "",
    status: "Faulty",
    source: "csv",
    dateImported: "20/05/2026 08:30 AM",
  },

  // ── ASH1 — Single batch (manual, MWS vendor) ───────────────────────────────
  {
    assetId: "ASH1-MWS-26-0001",
    batchId: "BCH-5E4F3A2B",
    category: "Laptop",
    condition: "New",
    brand: "Lenovo",
    model: "ThinkPad X1 Carbon",
    processor: "Intel Core i7",
    generation: "12th Gen",
    ram: "16GB",
    storage: "512GB SSD",
    speed: "2.1GHz",
    screenType: "Touch Screen",
    additionalInfo: "",
    status: "Ok",
    source: "manual",
    dateImported: "19/05/2026 02:00 PM",
  },
  {
    assetId: "ASH1-MWS-26-0002",
    batchId: "BCH-5E4F3A2B",
    category: "Laptop",
    condition: "New",
    brand: "Lenovo",
    model: "ThinkPad X1 Carbon",
    processor: "Intel Core i7",
    generation: "12th Gen",
    ram: "16GB",
    storage: "512GB SSD",
    speed: "2.1GHz",
    screenType: "Touch Screen",
    additionalInfo: "",
    status: "Ok",
    source: "manual",
    dateImported: "19/05/2026 02:00 PM",
  },

  // ── CONT4 — Single batch (csv, TTL vendor) ─────────────────────────────────
  {
    assetId: "CONT4-TTL-26-0001",
    batchId: "BCH-7B8C9D0E",
    category: "Workstation",
    condition: "New",
    brand: "Dell",
    model: "Precision 5820",
    processor: "Intel Xeon W",
    generation: "10th Gen",
    ram: "32GB",
    storage: "1TB SSD",
    speed: "3.7GHz",
    screenType: "",
    additionalInfo: "",
    status: "Ok",
    source: "csv",
    dateImported: "18/05/2026 10:45 AM",
  },
  {
    assetId: "CONT4-TTL-26-0002",
    batchId: "BCH-7B8C9D0E",
    category: "LCD",
    condition: "New",
    brand: "Dell",
    model: "U2722D",
    processor: "",
    generation: "",
    ram: "",
    storage: "",
    speed: "",
    screenType: "Non-Touch",
    additionalInfo: "",
    status: "Ok",
    source: "csv",
    dateImported: "18/05/2026 10:45 AM",
  },

  // ── ASH2 — Single batch (manual, TTL vendor) ───────────────────────────────
  {
    assetId: "ASH2-TTL-26-0001",
    batchId: "BCH-2F1E0D9C",
    category: "Laptop",
    condition: "Refurb",
    brand: "HP",
    model: "ProBook 450 G8",
    processor: "Intel Core i5",
    generation: "11th Gen",
    ram: "8GB",
    storage: "256GB SSD",
    speed: "2.4GHz",
    screenType: "Non-Touch",
    additionalInfo: "",
    status: "Ok",
    source: "manual",
    dateImported: "17/05/2026 04:15 PM",
  },
  {
    assetId: "ASH2-TTL-26-0002",
    batchId: "BCH-2F1E0D9C",
    category: "Laptop",
    condition: "Refurb",
    brand: "HP",
    model: "ProBook 450 G8",
    processor: "Intel Core i5",
    generation: "11th Gen",
    ram: "8GB",
    storage: "256GB SSD",
    speed: "2.4GHz",
    screenType: "Non-Touch",
    additionalInfo: "",
    status: "Faulty",
    source: "manual",
    dateImported: "17/05/2026 04:15 PM",
  },

  // ── CNT4 — Single batch (csv, TTL vendor) ──────────────────────────────────
  {
    assetId: "CNT4-TTL-26-0001",
    batchId: "BCH-9A8B7C6D",
    category: "Laptop",
    condition: "New",
    brand: "HP",
    model: "EliteBook 840 G9",
    processor: "Intel Core i5",
    generation: "12th Gen",
    ram: "16GB",
    storage: "512GB SSD",
    speed: "2.5GHz",
    screenType: "Non-Touch",
    additionalInfo: "",
    status: "Ok",
    source: "csv",
    dateImported: "13/06/2026 09:00 AM",
  },
  {
    assetId: "CNT4-TTL-26-0002",
    batchId: "BCH-9A8B7C6D",
    category: "Desktop",
    condition: "New",
    brand: "HP",
    model: "ProDesk 600 G6",
    processor: "Intel Core i7",
    generation: "10th Gen",
    ram: "16GB",
    storage: "512GB SSD",
    speed: "3.2GHz",
    screenType: "",
    additionalInfo: "",
    status: "Ok",
    source: "csv",
    dateImported: "13/06/2026 09:00 AM",
  },
];